### ISSUE TITLE
为什么我安装了插件后，scan里没有呢？

### ISSUE THREAD

**Issue by guangnian9988** [asd5772525/taluo#1]
![Uploading 图片_20240516160259.png…]()

**Comment by asd5772525** [comment]
看下你的日志，截图是本地图片 看不到

**Comment by guangnian9988** [comment]
> 看下你的日志，截图是本地图片 看不到

[INFO][2024-05-24 20:23:24][plugin_manager.py:254] - clone git repo: https://git                                                                                                                                   hub.com/asd5772525/taluo.git
Enumerating objects: 20, done.
Counting objects: 100% (20/20), done.
Compressing objects: 100% (17/17), done.
Total 20 (delta 7), reused 0 (delta 0), pack-reused 0
copied 19 pack entries19/20
WARNING: pip is being invoked by an old script wrapper. This will fail in a futu                                                                                                                                   re version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the unde                                                                                                                                   rlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip                                                                                                                                    directly.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '.                                                                                                                                   /plugins/taluo/requirements.txt'
[INFO][2024-05-24 20:23:25][wechat_channel.py:217] - [WX] sendMsg=Reply(type=INF                                                                                                                                   O, content=[INFO]
安装插件成功，请使用 #scanp 命令扫描插件或重启程序，开启前请检查插件是否需要配置                                                                                                                                   ), receiver=@f7062880e8f64668ed900634ae6eb93eb7afd7ac8dff6252a0c15183a3ef1eb7

**Comment by asd5772525** [comment]
scan一下之后看下日志呢 正常git之后应该是可以的 我这个没有requirements file 所以不用pip
你也可以把整个文件下载下来然后放在plugin文件夹里

**Comment by guangnian9988** [comment]
[INFO][2024-05-26 00:19:16][plugin_manager.py:254] - clone git repo: https://git                                                                                                                                   hub.com/asd5772525/taluo.git
Enumerating objects: 20, done.
Counting objects: 100% (20/20), done.
Compressing objects: 100% (17/17), done.
Total 20 (delta 7), reused 0 (delta 0), pack-reused 0
copied 19 pack entries19/20
WARNING: pip is being invoked by an old script wrapper. This will fail in a futu                                                                                                                                   re version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the unde                                                                                                                                   rlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip                                                                                                                                    directly.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '.                                                                                                                                   /plugins/taluo/requirements.txt'
[INFO][2024-05-26 00:19:18][wechat_channel.py:217] - [WX] sendMsg=Reply(type=INF                                                                                                                                   O, content=[INFO]
安装插件成功，请使用 #scanp 命令扫描插件或重启程序，开启前请检查插件是否需要配置                                                                                                                                   ), receiver=@980346ac82e3a523f6e86e99c6d2772bd2466cd487748305ed82dd912c66cad5
[INFO][2024-05-26 00:19:32][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module tool
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.tool.                                                                                                                                   tool
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin tool_v0.5 registered,                                                                                                                                    path=./plugins/tool
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module KFCwenan
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.KFCwe                                                                                                                                   nan.KFCwenan
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin KFCwenan_v1.0 registe                                                                                                                                   red, path=./plugins/KFCwenan
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module nicesuno
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.nices                                                                                                                                   uno.nicesuno
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Nicesuno_v1.2 registe                                                                                                                                   red, path=./plugins/nicesuno
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module MiniCPW-Plugi                                                                                                                                   n
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.MiniC                                                                                                                                   PW-Plugin.MiniCPW
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin ImageAnalysis_v1.0 re                                                                                                                                   gistered, path=./plugins/MiniCPW-Plugin
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module midjourney-pr                                                                                                                                   oxy-on-wechat
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.midjo                                                                                                                                   urney-proxy-on-wechat.mjapi
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.midjo                                                                                                                                   urney-proxy-on-wechat.mjcache
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.midjo                                                                                                                                   urney-proxy-on-wechat.ctext
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.midjo                                                                                                                                   urney-proxy-on-wechat.midjourney
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin MidJourney_v1.0.46 re                                                                                                                                   gistered, path=./plugins/midjourney-proxy-on-wechat
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module timetask
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.timet                                                                                                                                   ask.Tool
未安装ntchat: No module named 'channel.wechatnt'
未安装wework: No module named 'ntwork'
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.timet                                                                                                                                   ask.config
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.timet                                                                                                                                   ask.TimeTaskTool
未安装ntchat: No module named 'channel.wechatnt'
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.timet                                                                                                                                   ask.timetask
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin timetask_v2.8 registe                                                                                                                                   red, path=./plugins/timetask
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module linkai
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.linka                                                                                                                                   i.utils
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.linka                                                                                                                                   i.midjourney
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.linka                                                                                                                                   i.summary
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.linka                                                                                                                                   i.linkai
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin linkai_v0.1.0 registe                                                                                                                                   red, path=./plugins/linkai
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module role
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.role.                                                                                                                                   role
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Role_v1.0 registered,                                                                                                                                    path=./plugins/role
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module dungeon
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.dunge                                                                                                                                   on.dungeon
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Dungeon_v1.0 register                                                                                                                                   ed, path=./plugins/dungeon
[WARNING][2024-05-26 00:19:32][plugin_manager.py:113] - Failed to import plugin                                                                                                                                    WhalePlugin: No module named 'functions'
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module finish
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.finis                                                                                                                                   h.finish
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Finish_v1.0 registere                                                                                                                                   d, path=./plugins/finish
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module dailynotify
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.daily                                                                                                                                   notify.dailynotify
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin dailynotify_v0.1 regi                                                                                                                                   stered, path=./plugins/dailynotify
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.daily                                                                                                                                   notify.tools.morning_news
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.daily                                                                                                                                   notify.tools.weather
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.daily                                                                                                                                   notify.tools
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module hello
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.hello                                                                                                                                   .hello
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Hello_v0.1 registered                                                                                                                                   , path=./plugins/hello
[WARNING][2024-05-26 00:19:32][plugin_manager.py:113] - Failed to import plugin                                                                                                                                    taluo: unterminated string literal (detected at line 65) (taluopai.py, line 65)
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module jina_sum-main
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.jina_                                                                                                                                   sum-main.jina_sum
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin JinaSum_v0.0.1 regist                                                                                                                                   ered, path=./plugins/jina_sum-main
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module apiMusic
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.apiMu                                                                                                                                   sic.utils
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.apiMu                                                                                                                                   sic.api_plugins
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin apitools_v0.2 registe                                                                                                                                   red, path=./plugins/apiMusic
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module bdunit
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.bduni                                                                                                                                   t.bdunit
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin BDunit_v0.1 registere                                                                                                                                   d, path=./plugins/bdunit
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module apitools-main
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.apito                                                                                                                                   ols-main.utils
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.apito                                                                                                                                   ols-main.api_plugins
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin apitools_v0.2 registe                                                                                                                                   red, path=./plugins/apitools-main
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module keyword
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.keywo                                                                                                                                   rd.keyword
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Keyword_v0.1 register                                                                                                                                   ed, path=./plugins/keyword
[INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module banwords
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.banwo                                                                                                                                   rds.lib
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.banwo                                                                                                                                   rds.lib.WordsSearch
[INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.banwo                                                                                                                                   rds.banwords
[INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Banwords_v1.0 registe                                                                                                                                   red, path=./plugins/banwords
[timetask] inited
[timetask - INIT] config str: {
  "command_prefix": "$time",
  "debug": false,
  "time_check_rate": 1,
  "move_historyTask_time": "04:00:00",
  "is_open_route_everyReply": true,
  "is_open_extension_function": true,
  "is_need_title_whenNormalReply": true,
  "is_need_currentTime_whenNormalReply": true,
  "is_need_identifier_whenNormalReply": true,
  "is_need_detailDeccription_whenNormalReply": true,
  "extension_function":
  [
    {
      "key_word": "早报",
      "func_command_prefix":"$tool "
    },
    {
      "key_word": "点歌",
      "func_command_prefix": "$"
    },
    {
      "key_word": "搜索",
      "func_command_prefix": "$tool google "
    },
    {
      "key_word": "GPT",
      "func_command_prefix": "GPT"
    }
  ]
}
[INFO][2024-05-26 00:19:32][keyword.py:40] - [keyword] {}
[INFO][2024-05-26 00:19:32][keyword.py:42] - [keyword] inited.
[apitools] inited
[INFO][2024-05-26 00:19:32][KFCwenan.py:21] - [KFCwenan] inited
[INFO][2024-05-26 00:19:32][MiniCPW.py:22] - [ImageAnalysis] inited
Loaded as API: https://openbmb-minicpm-llama3-v-2-5.hf.space ✔
HTTP Request: GET https://openbmb-minicpm-llama3-v-2-5.hf.space/config "HTTP/1.1                                                                                                                                    200 OK"
HTTP Request: GET https://openbmb-minicpm-llama3-v-2-5.hf.space/info "HTTP/1.1 200 OK"
[INFO][2024-05-26 00:19:35][linkai.py:34] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2024-05-26 00:19:35][nicesuno.py:50] - [Nicesuno] inited
[INFO][2024-05-26 00:19:35][jina_sum.py:50] - [JinaSum] inited, config={'jina_reader_base': 'https://r.jina.ai', 'open_ai_api_base': 'https://api.gptgod.online/v1/', 'open_ai_api_key': 'sk-EtOqNbDiMJgmem0JT3CWpdOaBiwuwrf1cfantqBWLgzapnso', 'open_ai_model': 'gpt-3.5-turbo', 'max_words': 8000, 'white_url_list': [], 'black_url_list': ['https://support.weixin.qq.com', 'https://channels-aladin.wxqcloud.qq.com'], 'prompt': '我需要对下面的文本进行总结，总结输出包括以下三个部分：\n📖 一句话总结\n🔑 关键要点,用数字序号列出3-5个文章的核心内容\n🏷 标签: #xx #xx\n请使用emoji让你的表达更生动。'}
[INFO][2024-05-26 00:19:35][dailynotify.py:36] - [Dailynotify] inited
[INFO][2024-05-26 00:19:35][role.py:69] - [Role] inited
[INFO][2024-05-26 00:19:35][dungeon.py:56] - [Dungeon] inited
[INFO][2024-05-26 00:19:35][hello.py:38] - [Hello] inited
[INFO][2024-05-26 00:19:35][finish.py:23] - [Finish] inited
[INFO][2024-05-26 00:19:35][wechat_channel.py:217] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
插件扫描完成
发现新插件：
timetask_v2.8
Nicesuno_v1.2
Dungeon_v1.0
KFCwenan_v1.0
Finish_v1.0
linkai_v0.1.0
dailynotify_v0.1
Banwords_v1.0
ImageAnalysis_v1.0
tool_v0.5
Hello_v0.1
Keyword_v0.1
apitools_v0.2
JinaSum_v0.0.1
BDunit_v0.1
Role_v1.0
MidJourney_v1.0.46), receiver=@980346ac82e3a523f6e86e99c6d2772bd2466cd487748305ed82dd912c66cad5
[timetask - INIT] config str: {
  "command_prefix": "$time",
  "debug": false,
  "time_check_rate": 1,
  "move_historyTask_time": "04:00:00",
  "is_open_route_everyReply": true,
  "is_open_extension_function": true,
  "is_need_title_whenNormalReply": true,
  "is_need_currentTime_whenNormalReply": true,
  "is_need_identifier_whenNormalReply": true,
  "is_need_detailDeccription_whenNormalReply": true,
  "extension_function":
  [
    {
      "key_word": "早报",
      "func_command_prefix":"$tool "
    },
    {
      "key_word": "点歌",
      "func_command_prefix": "$"
    },
    {
      "key_word": "搜索",
      "func_command_prefix": "$tool google "
    },
    {
      "key_word": "GPT",
      "func_command_prefix": "GPT"
    }
  ]
}

**Comment by asd5772525** [comment]
[WARNING][2024-05-26 00:19:32][plugin_manager.py:113] - Failed to import plugin taluo: unterminated string literal (detected at line 65) (taluopai.py, line 65)
这段代码有点问题，我改了一下，重新安装就可以了

> [INFO][2024-05-26 00:19:16][plugin_manager.py:254] - clone git repo: https://git hub.com/asd5772525/taluo.git Enumerating objects: 20, done. Counting objects: 100% (20/20), done. Compressing objects: 100% (17/17), done. Total 20 (delta 7), reused 0 (delta 0), pack-reused 0 copied 19 pack entries19/20 WARNING: pip is being invoked by an old script wrapper. This will fail in a futu re version of pip. Please see [pypa/pip#5599](https://github.com/pypa/pip/issues/5599) for advice on fixing the unde rlying issue. To avoid this problem you can invoke Python with '-m pip' instead of running pip directly. ERROR: Could not open requirements file: [Errno 2] No such file or directory: '. /plugins/taluo/requirements.txt' [INFO][2024-05-26 00:19:18][wechat_channel.py:217] - [WX] sendMsg=Reply(type=INF O, content=[INFO] 安装插件成功，请使用 #scanp 命令扫描插件或重启程序，开启前请检查插件是否需要配置 ), receiver=@980346ac82e3a523f6e86e99c6d2772bd2466cd487748305ed82dd912c66cad5 [INFO][2024-05-26 00:19:32][plugin_manager.py:88] - Scaning plugins ... [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module tool [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.tool. tool [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin tool_v0.5 registered, path=./plugins/tool [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module KFCwenan [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.KFCwe nan.KFCwenan [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin KFCwenan_v1.0 registe red, path=./plugins/KFCwenan [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module nicesuno [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.nices uno.nicesuno [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Nicesuno_v1.2 registe red, path=./plugins/nicesuno [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module MiniCPW-Plugi n [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.MiniC PW-Plugin.MiniCPW [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin ImageAnalysis_v1.0 re gistered, path=./plugins/MiniCPW-Plugin [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module midjourney-pr oxy-on-wechat [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.midjo urney-proxy-on-wechat.mjapi [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.midjo urney-proxy-on-wechat.mjcache [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.midjo urney-proxy-on-wechat.ctext [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.midjo urney-proxy-on-wechat.midjourney [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin MidJourney_v1.0.46 re gistered, path=./plugins/midjourney-proxy-on-wechat [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module timetask [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.timet ask.Tool 未安装ntchat: No module named 'channel.wechatnt' 未安装wework: No module named 'ntwork' [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.timet ask.config [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.timet ask.TimeTaskTool 未安装ntchat: No module named 'channel.wechatnt' [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.timet ask.timetask [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin timetask_v2.8 registe red, path=./plugins/timetask [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module linkai [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.linka i.utils [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.linka i.midjourney [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.linka i.summary [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.linka i.linkai [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin linkai_v0.1.0 registe red, path=./plugins/linkai [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module role [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.role. role [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins/role [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module dungeon [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.dunge on.dungeon [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Dungeon_v1.0 register ed, path=./plugins/dungeon [WARNING][2024-05-26 00:19:32][plugin_manager.py:113] - Failed to import plugin WhalePlugin: No module named 'functions' [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module finish [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.finis h.finish [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Finish_v1.0 registere d, path=./plugins/finish [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module dailynotify [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.daily notify.dailynotify [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin dailynotify_v0.1 regi stered, path=./plugins/dailynotify [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.daily notify.tools.morning_news [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.daily notify.tools.weather [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.daily notify.tools [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module hello [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.hello .hello [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Hello_v0.1 registered , path=./plugins/hello [WARNING][2024-05-26 00:19:32][plugin_manager.py:113] - Failed to import plugin taluo: unterminated string literal (detected at line 65) (taluopai.py, line 65) [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module jina_sum-main [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.jina_ sum-main.jina_sum [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin JinaSum_v0.0.1 regist ered, path=./plugins/jina_sum-main [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module apiMusic [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.apiMu sic.utils [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.apiMu sic.api_plugins [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin apitools_v0.2 registe red, path=./plugins/apiMusic [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module bdunit [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.bduni t.bdunit [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin BDunit_v0.1 registere d, path=./plugins/bdunit [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module apitools-main [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.apito ols-main.utils [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.apito ols-main.api_plugins [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin apitools_v0.2 registe red, path=./plugins/apitools-main [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module keyword [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.keywo rd.keyword [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Keyword_v0.1 register ed, path=./plugins/keyword [INFO][2024-05-26 00:19:32][plugin_manager.py:103] - reload module banwords [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.banwo rds.lib [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.banwo rds.lib.WordsSearch [INFO][2024-05-26 00:19:32][plugin_manager.py:107] - reload module plugins.banwo rds.banwords [INFO][2024-05-26 00:19:32][plugin_manager.py:41] - Plugin Banwords_v1.0 registe red, path=./plugins/banwords [timetask] inited [timetask - INIT] config str: { "command_prefix": "$time", "debug": false, "time_check_rate": 1, "move_historyTask_time": "04:00:00", "is_open_route_everyReply": true, "is_open_extension_function": true, "is_need_title_whenNormalReply": true, "is_need_currentTime_whenNormalReply": true, "is_need_identifier_whenNormalReply": true, "is_need_detailDeccription_whenNormalReply": true, "extension_function": [ { "key_word": "早报", "func_command_prefix":"$tool " }, { "key_word": "点歌", "func_command_prefix": "$" }, { "key_word": "搜索", "func_command_prefix": "$tool google " }, { "key_word": "GPT", "func_command_prefix": "GPT" } ] } [INFO][2024-05-26 00:19:32][keyword.py:40] - [keyword] {} [INFO][2024-05-26 00:19:32][keyword.py:42] - [keyword] inited. [apitools] inited [INFO][2024-05-26 00:19:32][KFCwenan.py:21] - [KFCwenan] inited [INFO][2024-05-26 00:19:32][MiniCPW.py:22] - [ImageAnalysis] inited Loaded as API: https://openbmb-minicpm-llama3-v-2-5.hf.space ✔ HTTP Request: GET https://openbmb-minicpm-llama3-v-2-5.hf.space/config "HTTP/1.1 200 OK" HTTP Request: GET https://openbmb-minicpm-llama3-v-2-5.hf.space/info "HTTP/1.1 200 OK" [INFO][2024-05-26 00:19:35][linkai.py:34] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}} [INFO][2024-05-26 00:19:35][nicesuno.py:50] - [Nicesuno] inited [INFO][2024-05-26 00:19:35][jina_sum.py:50] - [JinaSum] inited, config={'jina_reader_base': 'https://r.jina.ai', 'open_ai_api_base': 'https://api.gptgod.online/v1/', 'open_ai_api_key': 'sk-EtOqNbDiMJgmem0JT3CWpdOaBiwuwrf1cfantqBWLgzapnso', 'open_ai_model': 'gpt-3.5-turbo', 'max_words': 8000, 'white_url_list': [], 'black_url_list': ['https://support.weixin.qq.com', 'https://channels-aladin.wxqcloud.qq.com'], 'prompt': '我需要对下面的文本进行总结，总结输出包括以下三个部分：\n📖 一句话总结\n🔑 关键要点,用数字序号列出3-5个文章的核心内容\n🏷 标签: #xx #xx\n请使用emoji让你的表达更生动。'} [INFO][2024-05-26 00:19:35][dailynotify.py:36] - [Dailynotify] inited [INFO][2024-05-26 00:19:35][role.py:69] - [Role] inited [INFO][2024-05-26 00:19:35][dungeon.py:56] - [Dungeon] inited [INFO][2024-05-26 00:19:35][hello.py:38] - [Hello] inited [INFO][2024-05-26 00:19:35][finish.py:23] - [Finish] inited [INFO][2024-05-26 00:19:35][wechat_channel.py:217] - [WX] sendMsg=Reply(type=INFO, content=[INFO] 插件扫描完成 发现新插件： timetask_v2.8 Nicesuno_v1.2 Dungeon_v1.0 KFCwenan_v1.0 Finish_v1.0 linkai_v0.1.0 dailynotify_v0.1 Banwords_v1.0 ImageAnalysis_v1.0 tool_v0.5 Hello_v0.1 Keyword_v0.1 apitools_v0.2 JinaSum_v0.0.1 BDunit_v0.1 Role_v1.0 MidJourney_v1.0.46), receiver=@980346ac82e3a523f6e86e99c6d2772bd2466cd487748305ed82dd912c66cad5 [timetask - INIT] config str: { "command_prefix": "$time", "debug": false, "time_check_rate": 1, "move_historyTask_time": "04:00:00", "is_open_route_everyReply": true, "is_open_extension_function": true, "is_need_title_whenNormalReply": true, "is_need_currentTime_whenNormalReply": true, "is_need_identifier_whenNormalReply": true, "is_need_detailDeccription_whenNormalReply": true, "extension_function": [ { "key_word": "早报", "func_command_prefix":"$tool " }, { "key_word": "点歌", "func_command_prefix": "$" }, { "key_word": "搜索", "func_command_prefix": "$tool google " }, { "key_word": "GPT", "func_command_prefix": "GPT" } ] }
